name: "OOO Pretty scary bug!"
description: Having a bug using the website????
body:
   - type: textarea
    attributes:
      label: Issue description
      placeholder: Briefly describe your issue here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: How to reproduce this bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: What is currently happening?
    validations:
      required: true
