blank_issues_enabled: true
contact_links:  
  - name: Usered official instance
    url: https://usered.ar.nf
    about: yes this doesn't have any sense ik.
  - name: Usered official instance's feedback page
    url: https://usered.ar.nf/feedback
    about: |
     >Prefering sending feedback on Usered*?
     >
     >*:Needs an available Usered account.
